### ISSUE TITLE
Frontend fetches many pages of praise data after login

### ISSUE THREAD

**Issue by mattyg** [CommonsBuild/praise#113]
Instead, it should only fetch a single page of praise data, the rest will be fetched as needed by the infinite scroll list.

**Comment by kristoferlund** [comment]
Yeah, the bottom scroll component gets triggered multiple times under certain circumstances. I looked into it before but didn't manage to figure out how to solve the issue.

**Comment by mattyg** [comment]
Unable to reproduce. Closing for now.
