### ISSUE TITLE
Disallow removal of active quantifiers from pool

### ISSUE THREAD

**Issue by mattyg** [CommonsBuild/praise#120]
If a quantifier is given some assignments for a period, an admin user can still remove their role as `QUANTIFIER` via the Quantifier Pool page. 

This would leave the data in an improper state, where the quantifier still has a bunch of assignments, but is unable to complete them.

We should implement a back-end check and front-end dialog to prevent removal of active quantifiers from the pool, or handle re-assigning their assignments.

**Comment by kristoferlund** [comment]
Disallowing removal would be the quick fix. 

Reassigning is a nice to have. If a quantifier drops of during quant an admin might want to reassign those praise to someone else.
