### ISSUE TITLE
Settings tied to periods

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#138]
See also #116

**Comment by kristoferlund** [comment]
UI?

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/74282ce3-8f63-4291-b7c0-91919e85e860)

**Comment by mattyg** [comment]
**Requirements**
- Some settings are globally defined
- Some settings are defined per-period
- Any settings defined per-period, should also have a corresponding global setting
- A setting that is defined for a specific period should not be able to be modified after that period has begun
- All settings specific to a period should be visible on that period's page.

**Comment by mattyg** [comment]
**Requirements**

- Some settings are globally defined
- Some settings are defined per-period
- Any settings defined per-period, should also have a corresponding global setting, to specify the default value of the per-period setting
- A per-period setting should can not be modified after that period has begun
- All per-period settings should be visible on that period's page.



**Settings Defined Per Period**

- PRAISE_QUANTIFIER_PER_PRAISE_RECEIVER
- PRAISE_PER_QUANTIFIER
- PRAISE_QUANTIFY_RECEIVER_PSEUDONYMS
- PRAISE_QUANTIFY_DUPLICATE_PRAISE_PERCENTAGE
- PRAISE_QUANTIFY_ALLOWED_VALUES



**UX**

- Modify the 'Create Period' page to include a section of the form to define all per-period settings. This section can be hidden by default.
- The per-period settings will be auto-filled with their corresponding global settings by default



**DB**

- Add a field *period* to the Setting model
  - If period is null: The setting is global
  - If period is ObectId: The setting is specific to the period

**Comment by kristoferlund** [comment]
> * Some settings are globally defined
> * Some settings are defined per-period
> * Any settings defined per-period, should also have a corresponding global setting, to specify the default value of the per-period setting
> * A per-period setting should can not be modified after that period has begun
> * All per-period settings should be visible on that period's page.

Yes! Agree 100%

> * PRAISE_QUANTIFIER_PER_PRAISE_RECEIVER
> * PRAISE_PER_QUANTIFIER
> * PRAISE_QUANTIFY_RECEIVER_PSEUDONYMS
> * PRAISE_QUANTIFY_DUPLICATE_PRAISE_PERCENTAGE
> * PRAISE_QUANTIFY_ALLOWED_VALUES

✅

### UX

We need to make room for more stuff on the periods page. Things like.. analytics will be coming. 

I propose this:

* A newly created period by default inherits global settings
* Settings are displayed on a "subpage"
* Quantifiers and Receivers are also broken out to subpages

<img width="2487" alt="image" src="https://user-images.githubusercontent.com/9698363/159242586-f0974456-db50-4480-a8e0-ae5f7fb8aefc.png">

See details here: https://miro.com/app/board/o9J_lyTkWjY=/?invite_link_id=452760982214

Using subpages like this has been the plan all along, I'll send you another reference image on Discord.

We will want to make a similar adjustment for the Quantifier pool page quite soon as well, turning it into more of a user admin page.

> * If period is ObectId: The setting is specific to the period

This means datamodel allows any setting to be overridden. Which is not necessarily a problem if we control in the UI which settings can be changed. But, if we further on will allowed uncontrolled access to the API then it might be good to more tightly specify what can be overridden. I don't know, torn here. Perhaps this setup is good for now, let's not overcomplicate things.
