### ISSUE TITLE
distinguish weekly cycles on quantification UI 

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise#143]
We need to find a way to make it more obvious on which day a praise was made and on which week a praise was made - this will be important for quantifiers to understand which weekly cycle a praise was a part of it and if a praise would be considered a duplicate of another. We could put dividers between weeks on the UI and as well for days or create tags on the praise for each day of the week (Monday, Tuesday, Wednesday ... ) Some color codes would be nice to add some flavour. ;)

![image](https://user-images.githubusercontent.com/67759413/157261906-4b331d2e-d883-4cbd-8910-9b7ba412ebc7.png)

**Comment by kristoferlund** [comment]
@nebs-dev Let's add a simple divider to begin with:

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/11bae90a-aaaa-471a-be5f-9ca69fae3f90)
