### ISSUE TITLE
automate sending DMs to drafted quantifiers

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise#145]
It's been proven ineffective to tag quantifiers within discord - it gets lost in the sea of notifications and quantifiers won't realize they have been drafted to quantify praise, which is important since this is a time sensitive process. 

It would be cool if the praise bot could send DMs to quantifiers that have been drafted to quantify in the praise dashboard notifying them they have been drafted and need to visit the dashboard and begin quantification

**Comment by Vyvy-vi** [comment]
kristofer:
> In general, I think we should try to avoid automation as much as possible. Unless we are really sure about the use case. One way of making this feature more flexible would be to add a messaging feature for admins. Admins can manually send messages to quantifiers from the dashboard and make some selection, like.. 
 > - Send message to all quantifiers assigned in a period
 > - .. to all that are not finished
 > - .. to all that are finished
    Oh.. and also sending messages to those in the quantifier pool.

**Comment by divine-comedian** [comment]
@Vyvy-vi 

We need some way to effectively notify Quantifiers - If we had the option to send out bulk messages with one button that would be super useful, we should notify them via Discord.

Definitely need a way to message quantifiers assigned to the period and quantifiers who have not finished.

**Comment by kristoferlund** [comment]
I discussed with @Vyvy-vi about sending messages directly from Discord. Something like this:

```
/praise-admin msg-quantifier-pool msg:[string]
/praise-admin msg-quantifiers done:[done | not done | all] period:[periodId] msg:[string]
```

`periodId` would ideally be in the form of an autosuggest where admin types "Aug..." it gets completed to "August 2021".

One benefit of sending messages from within Discord is that you can easily reference users, channels etc.

@Vyvy-vi do you think the setup above could work?

**Comment by Vyvy-vi** [comment]
yes, totally!
I think to make things simpler, we can separate out the scope(done, all, not done) into buttons
The auto-completion can be enforced via using an Option field

**Comment by Vyvy-vi** [comment]
this would look something like -
`/praise-admin annoncement content: string`
Bot replies to the message with the value of the content `arg` from command(as a preview).
This message has buttons - Confirm | Cancel
On Confirming, the bot replies with a button menu -
- Send to All Quantifiers
- Send to currently drafted quantifiers
- Send to currently drafted quantifiers that are done
- Send to currently drafted quantifiers that are not done
- Send to some Quantifiers
(last option allows to choose constraints)

**Comment by divine-comedian** [comment]
looks a bit complicated and easy to fat finger with all these variables you have to enter into a chat box. 

Is there no way to have simply a set of buttons an admin can see while viewing a particular quant?
