### ISSUE TITLE
Cannot update number settings

### ISSUE THREAD

**Issue by mattyg** [CommonsBuild/praise#149]
**Steps to Reproduce:**
- visit settings page
- change the value in PRAISE_PER_QUANTIFIER or PRAISE_QUANTIFY_DUPLICATE_PRAISE_PERCENTAGE
- save settings

You will get an error response from the server:
`Settings validation failed: type: Validator failed for path 'type' with value 'Number'`
and the settings will remain unchanged on refresh

**Comment by kristoferlund** [comment]
@nebs-dev I can confirm getting the same error.
