### ISSUE TITLE
Replicated praise appearing in quant

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise#160]
I have found from time to time instances of  exact duplicate praise while quantifying - same date, same text, same praiser - Perhaps this was a mistake on the user end when entering data or something in the db, not sure. 

At any rate maybe a filter if one praise is an exact match of another we can remove it from the db? worth investigating how this appears

![image](https://user-images.githubusercontent.com/67759413/158408230-34d4f281-59ef-4274-a429-11ba9d7fd19d.png)

**Comment by kristoferlund** [comment]
First praise seems to be have sent twice

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/8d685304-2a07-47d9-bd1f-b97f1c4fdefa)

**Comment by mattyg** [comment]
Closing this ticket -- I'll  create a new one for the enhancement to automatically not include praise that appears accidentally duplicated.
