### ISSUE TITLE
Setup production server without Dockerizing api/frontend/bot

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#169]
- Startup another server on Digital Ocean  
- Set it up manually. 
- Document the process and add to the documentation.
- Use this server as production server for now and point praise.tecommons.org.
- The current 68.xx server we be retired

**Comment by mattyg** [comment]
You might also consider just deploying to a PaaS -- something like heroku or render.com. It would significantly reduce the setup required.
