### ISSUE TITLE
Embed links inside the praise reason

### ISSUE THREAD

**Issue by Vyvy-vi** [CommonsBuild/praise#179]
I think it might be really neat if the links inside the praise reason are clickable in future. (this allows the praise givers to give more context about their praise)

![Screenshot 2022-03-18 at 12 29 21 AM](https://user-images.githubusercontent.com/62864373/158876515-294428d1-61a2-411c-bc72-1c95da7c7d85.png)

**Comment by Vyvy-vi** [comment]
*while this isn't very important, it can be something that we couple with #156, if we're making a custom format for storing references to discord objects

**Comment by kristoferlund** [comment]
Agree 100%! 

It doesn't top the feature list but I definitely would like to add this quite soon.

Have a look at these:
https://oembed.com/
https://www.npmjs.com/package/react-oembed-container

**Comment by kristoferlund** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/9698363/161702720-9fbcc4bd-995d-485a-9f7a-5af11ff5f53a.png">

**Comment by kristoferlund** [comment]
https://npm.io/package/unfurl.js
