### ISSUE TITLE
Audit & resolve any issues with timezone handling

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise#204]
I noticed a few times now when I am creating a new quant period as an admin I can select the end date of the period. However when I choose the end date and create the period the end date shown is the day before the end date I selected. 

![image](https://user-images.githubusercontent.com/67759413/160131317-531dd084-9f07-4b85-bc46-c14baf4cb55f.png)

i.e 

September 2021 - I set the end date as the 30th - end date displayed is the 29th 
October 2021 - I set the end date as the 31st - end date displayed is the 30th. 

I think it makes the most sense to include praise data up to and including the end date selected. Right now it's a bit confusing

**Comment by kristoferlund** [comment]
Yeah, we need to get to the bottom of this and decide how to work with dates. Timezones are thing that makes this complicated. 

Discord servers, our server, the individual users etc. They all live in different timezones. Which means your 30th might be my 31st. 

But yes, the general rule is: Praise belongs to a period if their date is greater than previous period end date **and** up to and including the current period end date.

@Vyvy-vi @mattyg @nebs-dev do you know of any best practices when it comes to handling dates in a multi timezone environment?

**Comment by mattyg** [comment]
> @Vyvy-vi @mattyg @nebs-dev do you know of any best practices when it comes to handling dates in a multi timezone environment?

- store all datetimes as UTC
- on render: convert datetime to user's local timezone (i.e. whatever browser tells you)
- on input: convert datetime from user's local timezone to UTC

**Comment by mattyg** [comment]
I realized that even with timezone handling as described there are still some trade-offs for how to handle manually-entered times. Currently the only manually entered times are by admin users when creating / updating a period end date.

I wanted to get your thoughts before merging #228. I implemented option 2 for now, but don't really have a strong preference.

**Options for Period end date input handling**

- **option 1:** Keep the same UX to create and update period.endDate. BUT, upon submit take the received day, add a time of `23:59:59.999`, convert from user's timezone to UTC and submit to the server.
  - Pros: 
    - All users always see localized times. I think the simplest and clearest user experience.
  - Cons: 
    - The database data for period.startDate and period.endDate looks a bit less "clean" (because UTC times will vary, instead of all being "00:00:00").
    - If multiple admin users in different timezones try to create periods 1 week apart, the periods will not be exactly 1 week apart. To resolve this, we may need a feature to generate the new period.endDate based on the previous period's.
- **option 2:** Modify the UX to create, update, and display period.endDate as UTC, with the text "UTC"
  - Pros:
    - database data is a bit "cleaner" looking
    - Admins in different timezones can create periods exactly X days apart through the current UX
  - Cons:
    - Mental overhead for admins to convert their local time to UTC to make sense of the date they're inputting. To resolve this, we may still want a feature to generate the new period.endDate based on the previous period's.

**Comment by mattyg** [comment]
> So **option 1**, for a period that spans November 2021:
> 
> * The period begins after the end of last period ($gt): `2021-10-31T23:59:59.999Z`
> * The period ends at the period end date ($lte): `2021-11-30T23:59:59.999Z`
> 
> Did I understand that correctly? I think that is a good idea.

Yes. It would mean that shortending the date to "2021-11-30" would actually mean "up to and including 2021-11-30"

**Comment by kristoferlund** [comment]
Yeah, you are right UTC dates for `praise.createdDate` is probably just confusing. The Discord way of presenting the dates is nice, with a short relative date written out and the full date on hover.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/9698363/161813207-fad73da4-02d0-46c5-a9dd-72e200ee70d7.png">

`period.endDate` - The main thing is here I don't see the admins timezone being relevant when a new period is created. The period length should not be affected by who presses the create button. The reasonable thing then (I believe) is to use UTC without conversion when creating. Choosing October 31, 2021 in the selector always sets the endDate to `2022-10-31T23:59:59.999Z` no matter who presses the button.

**Comment by mattyg** [comment]
> `period.endDate` - The main thing is here I don't see the admins timezone being relevant when a new period is created. The period length should not be affected by who presses the create button. The reasonable thing then (I believe) is to use UTC without conversion when creating. Choosing October 31, 2021 in the selector always sets the endDate to `2022-10-31T23:59:59.999Z` no matter who presses the button.

I think that makes sense. I'll just make sure to explicitly display `UTC` on the period dates and the Period create /update forms -- so admins know that they are choosing a UTC date (not their own timezone's).

**Comment by mattyg** [comment]
> Yeah, you are right UTC dates for `praise.createdDate` is probably just confusing. The Discord way of presenting the dates is nice, with a short relative date written out and the full date on hover.

I like this UX but I'm going to split it off into a new 'enhancement' ticket #249
