### ISSUE TITLE
ufw Docker Rules Add ufw Will Not Restart

### ISSUE THREAD

**Issue by CFWHISPERER** [CommonsBuild/praise#206]
After adding the Docker rules to after.rules in the Firewall ufw will not restart...

root@ubuntu-20:/etc/ufw# systemctl restart ufw
Job for ufw.service failed because the control process exited with error code.
See "systemctl status ufw.service" and "journalctl -xe" for details.
root@ubuntu-20:/etc/ufw# systemctl restart ufw
root@ubuntu-20:/etc/ufw#

**Comment by CFWHISPERER** [comment]
This is on a Ubuntu 20.04 Droplet

**Comment by CFWHISPERER** [comment]
@kristoferlund thank you for adding the devops label I will make sure to do so in future.

**Comment by kristoferlund** [comment]
Great, closing.
