### ISSUE TITLE
The old praise retirement bot / give error message when using the old praise bot.

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#218]
I think we should push a new version of the old praise bot once we retire it. If using the old praise bot you receive a reply like this:

```
This praise bot has been retired, your praise has not been registered. Try the new praise bot useing the /praise command.
```

**Comment by kristoferlund** [comment]
But oh wait, Commons Stack is using the same bot right? Then this is not a good idea.

**Comment by Vyvy-vi** [comment]
We could hardcode the old bot to not work in the TEC server

**Comment by Vyvy-vi** [comment]
Or we could just remove the old bot and have this one catch the text content `!praise` from user messages and respond with the above message

**Comment by kristoferlund** [comment]
@Vyvy-vi could you place this next on your list after the issues you are currently working on?

**Comment by Vyvy-vi** [comment]
yes.

**Comment by Vyvy-vi** [comment]
depends on https://github.com/hurek/Praise-Bot-Discord/pull/5
