### ISSUE TITLE
Blocks Settings Prevent Nginx From Restarting

### ISSUE THREAD

**Issue by CFWHISPERER** [CommonsBuild/praise#227]
After applying the Blocks settings, Nginx will not restart-start, so I am working through this and will update with progress.

**Comment by mattyg** [comment]
@CFWHISPERER Have you considered using Caddy for the reverse proxy instead of nginx? It's absurdly simple to setup and configure. https://caddyserver.com/

**Comment by CFWHISPERER** [comment]
Thanks I will look into that.

**Comment by CFWHISPERER** [comment]
Solved this, the directions for setting up blocks in these guidelines https://github.com/CommonsBuild/praise/blob/dev/packages/docs/install-digital-ocean.md  has this line "Nginx comes with a default startpage that runs on port 80. Remove that:" this is incorrect and causes Nginx to fail on start-up.  There are other slight omissions so I am going through the whole install, physically and correcting where needed.  I also started to look into Caddy as suggested by @mattyg

**Comment by kristoferlund** [comment]
Caddy looks nice! Quite many steps to complete though to set it up on Digital Ocean, at least according to this guide: https://www.digitalocean.com/community/tutorials/how-to-host-a-website-with-caddy-on-ubuntu-18-04

But perhaps there is a more straightforward way?

@CFWHISPERER if Nginx doesn't start, also compare the settings with the ones used on the current production server. They should be fairly identical.

Also, I set up a domain you can use in the config: dev1.givepraise.xyz

**Comment by mattyg** [comment]
> Caddy looks nice! Quite many steps to complete though to set it up on Digital Ocean, at least according to this guide: https://www.digitalocean.com/community/tutorials/how-to-host-a-website-with-caddy-on-ubuntu-18-04
> 
> But perhaps there is a more straightforward way?
> 
> @CFWHISPERER if Nginx doesn't start, also compare the settings with the ones used on the current production server. They should be fairly identical.
> 
> Also, I set up a domain you can use in the config: `dev1.givepraise.xyz`

**Comment by mattyg** [comment]
I w

> Caddy looks nice! Quite many steps to complete though to set it up on Digital Ocean, at least according to this guide: https://www.digitalocean.com/community/tutorials/how-to-host-a-website-with-caddy-on-ubuntu-18-04
> 
> But perhaps there is a more straightforward way?
> 

Yeah I would do it all through docker -- something like this https://github.com/lucaslorentz/caddy-docker-proxy#basic-usage-example-using-docker-compose
