### ISSUE TITLE
/help

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#232]
- How to mention users `@user`
- Link to `/docs` for more information when that is up

`/activate`
- To link your eth address to your Discord account and to give you praise powers
- Eth address needed for rewards payout

`/praise`
- Short instruction about praise reason

`/forward`
- Difference between you and giver

`/whoami`

**Comment by kristoferlund** [comment]
@Vyvy-vi I wrote some notes anyway 👆

**Comment by Vyvy-vi** [comment]
How thoroughly do we want the command help to be?
- Do we want to list help for all subcommands?
- Do we want to list descriptions of the command options?
