### ISSUE TITLE
Serve docs package at /docs

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#252]
Modify install instructions for nginx so that we serve the contents of the docs package on `/docs`.

**Comment by CFWHISPERER** [comment]
Just taking a look at this @kristoferlund, can you expand a little on what is needed here; thank you.

**Comment by kristoferlund** [comment]
I'm closing this. I think we should reconsider if docs should be part of the installation package. We might setup a separate repository for docs.
