### ISSUE TITLE
Serving of uploaded images don't work

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#261]

**Comment by mattyg** [comment]
Is this the same issue as the missing sidebar image on production? We were missing the new env variable `SERVER_URL` added in #209.

Might be good to start checking for all required env variables on startup. I'll make a ticket for it.

**Comment by kristoferlund** [comment]
I have a fix for this issue in the upcoming Dockerisation PR. 

> Might be good to start checking for all required env variables on startup. I'll make a ticket for it.

Agree!
