### ISSUE TITLE
"/admin announce" don't work

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#262]
The command crashes trying to send PeriodSelectMenu, when the "All assigned quantifiers" or "All unfinished quantifiers" options are selected.
The command works as expected when selecting "All users" or "All quantifiers".

**Comment by Vyvy-vi** [comment]
I'm unable to reproduce the same in my development environment

**Comment by Vyvy-vi** [comment]
*all is well, the command works
It was erroring out since there were no periods open for quantification when testing.
(we would need to add a check for this to the command)
