### ISSUE TITLE
Bash install script

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#281]
Now that we have packaged the system as Docker containers it should be fairly easy to write a shell script for the server install. 

Ideally we would like to make the install as simple as this:

```
git clone https://github.com/CommonsBuild/praise.git
cd praise
sh install.sh
```

`install.sh` in turn sets up Docker and asks user to configure the system.

After install script has completed, user should only have to type `yarn start` to start Praise.

**Comment by kristoferlund** [comment]
I tried fetching input from the user, it seems quite straightforward using bash.

```
#!/bin/bash

export $(cat .env | xargs)

read -p "What domain does this server run on? [$SERVER]:"

echo "$REPLY" > somefile
```

**Comment by mattyg** [comment]
It may also be 

> I tried fetching input from the user, it seems quite straightforward using bash.
> 
> ```
> #!/bin/bash
> 
> export $(cat .env | xargs)
> 
> read -p "What domain does this server run on? [$SERVER]:"
> 
> echo "$REPLY" > somefile
> ```

Might be preferable to keep it in typescript so new developers don't need to learn bash scripting. Were using `yargs` to parse inputs in one of the api cli commands. Here's a few other similar packages for js that might have better support for "interactive" input: https://www.npmtrends.com/inquirer-vs-prompts-vs-yargs-vs-yargs-interactive

**Comment by kristoferlund** [comment]
Instead of creating a complete install script in bash, lets just make a short bash stub that checks for and installs node. And the rest of the script is written in typescript.
