### ISSUE TITLE
Setup staging server

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#283]
Setup the staging server using the new install instructions, currently found on the `feat/dockerisation` branch.

IP: 161.35.158.157
Domain: staging.givepraise.xyz

**Comment by CFWHISPERER** [comment]
I am almost there with Staging set-up, just have what looks like a MongoDB credentials issue.  I have created a detailed step-through of what I did here in Notion.   Having not used Notion before I hope this is appropriate, if not, please let me know, thank you https://www.notion.so/Installation-Guide-0415-22-6a316061f7b24ec7833afb1a919075c2

**Comment by CFWHISPERER** [comment]
I meant to mention, the details are in an attached .odt file.

**Comment by kristoferlund** [comment]
> I meant to mention, the details are in an attached .odt file.

Nice! You can use Notion as a regular text editor as well and paste the full text there. I do not find the attached `.odt`.

Have you been using the updated install instructions found on the `feat/dockerisation` branch?

https://github.com/CommonsBuild/praise/blob/feat/dockerisation/packages/docs/install-praise-on-digital-ocean.md

**Comment by CFWHISPERER** [comment]
Here is the latest status; this is what I get on QA when running docker compose up in /root/feat/dockerization/

root@tec-praise-staging:~/feat/dockerization# docker compose up -d
WARN[0000] The "MONGO_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MONGO_USERNAME" variable is not set. Defaulting to a blank string. 
[+] Running 0/1
 ⠿ discord-bot Error                                                                                                                                    1.5s
Sending build context to Docker daemon  375.2MB
Step 1/13 : FROM node:16.13.2-alpine
 ---> 23990429c0d7
Step 2/13 : WORKDIR /usr/src/
 ---> Using cache
 ---> 29e085080146
Step 3/13 : COPY ./package*.json .
 ---> Using cache
 ---> f3755f4e9396
Step 4/13 : COPY ./.yarnrc.yml .
 ---> Using cache
 ---> 4b626893081b
Step 5/13 : COPY ./yarn.lock .
 ---> Using cache
 ---> e73673877d2f
Step 6/13 : COPY ./.env .
 ---> Using cache
 ---> 40fa4d7d2fdc
Step 7/13 : COPY ./.yarn ./.yarn
 ---> Using cache
 ---> a32c389ff24f
Step 8/13 : COPY ./packages/api ./packages/api
 ---> Using cache
 ---> 56e9b59ca003
Step 9/13 : COPY ./packages/discord-bot ./packages/discord-bot
 ---> Using cache
 ---> d808a9da69db
Step 10/13 : RUN yarn set version berry
 ---> Using cache
 ---> c232da1d379b
Step 11/13 : RUN yarn
 ---> Using cache
 ---> 89369b915b20
Step 12/13 : RUN yarn workspace api build
 ---> Running in 3bdbcf521200
src/scripts/replace-quantifier.ts(6,19): error TS7016: Could not find a declaration file for module 'yargs'. '/usr/src/node_modules/yargs/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/yargs` if it exists or add a new declaration (.d.ts) file containing `declare module 'yargs';`
1 error occurred:
        * Status: The command '/bin/sh -c yarn workspace api build' returned a non-zero code: 2, Code: 2
