### ISSUE TITLE
Order Settings

### ISSUE THREAD

**Issue by Vyvy-vi** [CommonsBuild/praise#299]
With the addition of new settings, the older order of praise settings looks unpolished. It would be great if we could add an implementation for ordering and grouping the settings.

![image setting in middle](https://cdn.discordapp.com/attachments/895054667921379331/964319467003859024/Screenshot_2022-04-15_at_5.48.21_AM.png)

**Comment by kristoferlund** [comment]
This issue is also described in #131, closing.
