### ISSUE TITLE
Docker uses 100% CPU

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#383]

**Comment by kristoferlund** [comment]
Problem was: `pm2` was still running node services even though I thought to have uninstalled it. Now fixed.

<img width="998" alt="Skärmavbild 2022-05-12 kl  09 47 31" src="https://user-images.githubusercontent.com/9698363/168023424-eacad8fe-5910-42dc-948f-5737daf2e5c8.png">

**Comment by mattyg** [comment]
awesome! thanks for digging into that!
