### ISSUE TITLE
Improve quantifier assign distribution

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#95]

**Comment by mattyg** [comment]
@kristoferlund Can you elaborate on the goal of this issue? What is the ideal distribution of assignments?

**Comment by kristoferlund** [comment]
@mattyg 

The current algorithm is unable to produce an even distribution. The assigned praise count drops of towards the end. See image below:

![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/9d92d0db-af56-492b-9bcb-6a368052b67f)

The goal for the assignment is to get every quantifier as close to the `PRAISE_PER_QUANTIFIER` number of assigned praise as possible. 

- Each praise should be quantified by `PRAISE_QUANTIFIERS_PER_PRAISE_RECEIVER` number of quantifiers.
- When assigned, the quantifier must be assigned all receiver praise for one period. 
- Users **are not** allowed to quantify their own received praise 
- Users **are** allowed their own given praise

**Comment by mattyg** [comment]
I think these two requirements can conflict:

> The goal for the assignment is to get every quantifier as close to the PRAISE_PER_QUANTIFIER number of assigned praise as possible.

> When assigned, the quantifier must be assigned all receiver praise for one period.

Assume `X` is the number of praise items someone was dished in a period. 

Then if `X > PRAISE_PER_QUANTIFIER` we can only get one of these requirements fulfilled. i.e. either (1) the quantifiers are assigned **all** X praise items, or (2) they are assigned **only** `PRAISE_PER_QUANTIFIER` items (and other quantifiers are brought in for the rest).

Which should the algorithm do in this case?

Also, what was the original goal behind this requirement?
> When assigned, the quantifier must be assigned all receiver praise for one period."

Is it solely to enable quantifiers to identify and mark duplicates? Perhaps a long-term alternative could be to separate the task of quantification from duplicate-detection. I.e. have duplicate-detectors review *all* praise items for a recipient and mark duplicates, freeing up quantifiers to quantify any random selection of praise instances without regard to who the recipients are.

**Comment by kristoferlund** [comment]
> Assume `X` is the number of praise items someone was dished in a period.
> 
> Then if `X > PRAISE_PER_QUANTIFIER` we can only get one of these requirements fulfilled. Either (1) the quantifiers are assigned **all** X praise items, or (2) they are assigned **only** `PRAISE_PER_QUANTIFIER` items (and other quantifiers are brought in for the rest).

Yes, the second rule currently takes precedence over the first.

```
        ((q.receivers.length === 0 && r.praiseCount >= praisePerQuantifier) ||
          assignedPraiseCount(q) + r.praiseCount < maxPraisePerQuantifier)
```

If quantifier have not been assigned any receivers and `praiseCount` is greater than `PRAISE_PER_QUANTIFIER`, assign all those Praise to that quantifier. 

But, in reality that will most likely not occur. I created an unusually long Praise period yesterday - 6 weeks. The top receiver got ca 140 Praise during that period. And we believe a good value for `PRAISE_PER_QUANTIFIER` to be somewhere between 200-300. 

> Also, what was the original goal behind this requirement:
> 
> > When assigned, the quantifier must be assigned all receiver praise for one period."
> 
> Is it solely to enable quantifiers to identify and mark duplicates? If so, perhaps a long-term alternative could be to separate the task of quantification from duplicate-detection. I.e. have duplicate-detectors review _all_ praise items for a recipient and mark duplicates, freeing up quantifiers to quantify any random selection of praise instances without regard to who the recipients are.

Yes, solely for the quantifiers to be able to identify dupes within a Period. Without that rule the algorithm becomes super simple. I'll add "duplicate-detectors" as a separate issue to investigate and discuss.

**Comment by mattyg** [comment]
This should be significantly improved from #129  & #129. However there are still some issues with the distribution
- With the "first fit descending", "next fit" and "best fit descending" bin-packing algorithm, the last bin acts as overflow and will likely be much smaller than the max capacity. For our usage, bin-packing is run once for every redundant copy of praise as set by `PRAISE_QUANTIFIERS_PER_PRAISE_RECEIVER`, and so we will have that number of undersized collections of praise assigned.


It we want to smooth out the distribution of the last bins, it might require a more rigorous approach to improving our bin-packing algorithm that I can offer, perhaps with some help from data-scientists.

**Comment by kristoferlund** [comment]
The distribution is definitely good enough for now! Great work!
