### ISSUE TITLE
Speed up calculation of praise score

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise#96]

**Comment by mattyg** [comment]
Note from kristofer:

> For #96, one easy solution I haven't thought about is calculating the praise score not at fetch but at save. A new field would be added to Praise - score and using a pre-save hook, the value is calculated each time the Praise object is saved. I don't like it because it means duplication of data - if the pre-save hook for some reason doesn't run the score and the quantifications could end up out of sync. But.. the optimisation effect is great and the risk of the hook not running is small so perhaps it is an ok tradeoff?

**Comment by mattyg** [comment]
@kristoferlund Can you clarify which frontend page or request appears to be running noticeably slow? It looks like we have several different places where praise is calculated, so I'd like to confirm I'm addressing the issue properly. Thanks

**Comment by kristoferlund** [comment]
Yeah, loading period details from the backend is slow after quantifiers have been assigned. The offender is this function in `period/controllers.ts`:

```
118   await calculateReceiverScores(receivers);
```
